project:
  type: website

website:
  title: "On the calibration of powerset speaker diarization models"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        icon: card-list
        text: Index
      - href: calibration.qmd
        text: Calibration
        icon: reception-4
      - href: finetuning.qmd
        text: Finetuning
        icon: sliders2-vertical
      - href: validation.qmd
        text: Validation
        icon: database

      # - href: blog.qmd
      #   icon: journal-text
      #   text: Blog

format:
  html:
    theme:
      light: united
    css: styles.css
    toc: true


